name: Test

on:
  workflow_dispatch:
  
jobs:
  test-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Check Variables
      run: |
         echo "Valor real de la variable secreta: ${{ secrets.$GPG_KEY_ID }}"
         echo "Valor real de la variable secreta: ${{ secrets.$GPG_PASS}}"
         echo "Valor real de la variable secreta: ${{ secrets.$GPG_P_KEY }}"
         
         
         
