name: Test

on:
  workflow_dispatch:

jobs:
  test-repo:
    runs-on: ubuntu-latest      
      
    steps:
      # Install dependencies required by the scripts
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg    
      - name: List keys
        run: |
          echo "${{secrets.GPG_P_KEY}}" | tr ';' '\n' > GPG-KEY-pmanager
          gpg --import GPG-KEY-pmanager
